### PR TITLE
Started unit testing price calculation service

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
I was not sure about your unit testing methodology, so I created this small implementation to see how you guys would react... if that approach is OK I will create more tests

### CODE REVIEW

**Comment by Leonardo-Ferreira** [comment]
@KrzysztofPajak my comment on #730 was actually aimed at this PR here, sorry about the confusion

**Comment by KrzysztofPajak** [comment]
@Leonardo-Ferreira 
Why you set method GetAllowedDiscountsAppliedToAllProduct as Internal ?
Please restore to protected and remove line: [assembly: InternalsVisibleTo("Grand.Services.Tests")]
Then I will merge.

**Comment by Leonardo-Ferreira** [comment]
well that is the thing...
in order to unit test a method from outside, they either can't be private, or you have to test them via reflection.
To not make them public, one "workaround" is to make them `internal` and annotate the namespace with `InternalsVisibleTo`. This annotation instructs them compiler to allow the referenced assembly ONLY to peak into the internals methods of the annotated namespace.
Since we already consume the functionalities over interfaces, there's no harm done making them internal...

If I were to revert this, I either would have to move the unit tests into the class itself, or perform them via reflection (this would be messy)

**Comment by Leonardo-Ferreira** [comment]
Any concerns @KrzysztofPajak?
This is a well documented solution here a 3 references:

- http://anthonygiretti.com/2018/06/27/how-to-unit-test-internal-classes-in-net-core-applications/
- http://blog.tdwright.co.uk/2017/09/19/testing-without-compromise-using-internalsvisibleto/
- https://stackoverflow.com/questions/1211707/how-to-access-classes-in-another-assembly-for-unit-testing-purposes

**Comment by KrzysztofPajak** [comment]
Sory but I don't want change file Grand.Services by adding InternalsVisibleTo.
We need to find another way.

**Pull request closed without merging**
