### PR TITLE
 #588 Add filter by store on bulk edit product page

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi Dmitriy,
I suppose it won't work correctly in the case of Staff users. Did you checked it with user with assigned Staff role? It should see only products from his store.

**Comment by dborovsky** [comment]
Have undestood. I will check. Maybe I didnt undestand correct logic.

**Comment by dborovsky** [comment]
Hi Patryk, i changed a bit. Check please. If need something fix, tell me. Thanks

**Comment by KrzysztofPajak** [comment]
Hi,
File: Grand.Web/Areas/Admin/Services/ProductViewModelService.cs
Method: Task<(IEnumerable<BulkEditProductModel> bulkEditProductMode

I suggest you prepare variable storeId - because user (staff) can change model.SearchStoreId (by javascript).

My proposition:
var storeId = model.SearchStoreId;
if (_workContext.CurrentCustomer.IsStaff())
   storeId = _workContext.CurrentCustomer.StaffStoreId;

Regards
Krzysztof

**Comment by dborovsky** [comment]
Last commit was updated with this changes.

**Pull request merged**
