### PR TITLE
Issue no93

### PR DESCRIPTION
**Pull request by kirollosonsi**
Resolves #issueNumber  
Type: **feature|bugfix|**

## Issue
Possibility to automatically delete unpaid orders after X days.

## Solution
Hi,
I've add an int? Property "DaysToDeleteUnpaidOrder" which would be set to number of days to delete an unpaid order.
also creating a Background service which runs every day at midnight and check on the previous  Property and start perform deleting action.

## Testing
* add many orders having payment state of unpaid.
* change the timing at which background service run to be every 1 or 2 min for as a shortcut for testing

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
Hi @kirollosonsi 
Thanks for the pull request!
I think orders should not be deleted but canceled.
And you should use this mediator:
**await _mediator.Send(new CancelOrderCommand() { Order = order, NotifyCustomer = true });**
Orders to be canceled we should take not only not paid but also order status is pending.

**Comment by kirollosonsi** [comment]
Hi @KrzysztofPajak ,
I've used the **mediatR** mentioned above to cancel order instead of Delete order service

**Comment by KrzysztofPajak** [comment]
Hi @kirollosonsi 
Yes, I saw, thanks!
It would be great rename from Delete to Cancel (method name, settings).

**Comment by KrzysztofPajak** [comment]
Hi @kirollosonsi 
To support the new scheduled task please use our interface IScheduleTask (and remove your own IScheduledJobService). 
To register a new task in the system you need to implement install and upgrade process such as like this:
For the installation process you need to update this method:
https://github.com/grandnode/grandnode/blob/e9fa49b9602744a0db92b5f9e45c3007144f829b/Grand.Services/Installation/CodeFirstInstallationService.cs#L10311
For the upgrade process, you need to implement here:
https://github.com/grandnode/grandnode/blob/e9fa49b9602744a0db92b5f9e45c3007144f829b/Grand.Services/Installation/UpgradeService.cs#L998 
Sample code:
var tasks = _serviceProvider.GetRequiredService<IRepository<ScheduleTask>>();
            var endtask = new ScheduleTask {
                ScheduleTaskName = "Your task",
                Type = "Grand.Services.Tasks.YourTask, Grand.Services",
                Enabled = false,
                StopOnError = false,
                TimeInterval = 1440
            };
await tasks .InsertAsync(endtask);

**Comment by PatrykPorabik** [comment]
Hi @kirollosonsi how is it going? Would you finish this task?

**Comment by kirollosonsi** [comment]
Working on it, but I'm overloaded with tasks from my job to meet the dead line, sorry for being late

**Comment by PatrykPorabik** [comment]
Thanks a lot for your contribution!

**Pull request merged**
