### PR TITLE
Update routing to asp.net core 3.0

### PR DESCRIPTION
**Pull request by dborovsky**
#603

### CODE REVIEW

**Comment by dborovsky** [comment]
PR is not ready. I plane to update. wait please one commit, i will inform you to check.

**Comment by KrzysztofPajak** [comment]
@dborovsky 
For your information, odata is not supported endpoint yet. But team have plan to update odata for using endpoints :) - https://github.com/OData/WebApi/issues/1748
So you can comment code in Grand.API (related with IRouting).

**Comment by dborovsky** [comment]
Hi Krzysztof. 

If We move routing to Endpoint  we need implement interface IEndpointRouteBuilder. Correct? 

But... I have a bit problem there:
**Grand.Framework/Localization/LocalizedRouteExtensions**

For example I tried to change this method to IEndpointRouteBuilder:

```
public static IEndpointRouteBuilder MapLocalizedRoute(this IEndpointRouteBuilder routeBuilder,
            string name, string template, object defaults, object constraints, object dataTokens)
        {
            if (routeBuilder.DefaultHandler == null)
                throw new ArgumentNullException(nameof(routeBuilder));

            //get registered InlineConstraintResolver
            var inlineConstraintResolver = routeBuilder.ServiceProvider.GetRequiredService<IInlineConstraintResolver>();

            //create new generic route
            routeBuilder.Routes.Add(new LocalizedRoute(routeBuilder.DefaultHandler, name, template,
                new RouteValueDictionary(defaults), new RouteValueDictionary(constraints), new RouteValueDictionary(dataTokens),
                inlineConstraintResolver));

            return routeBuilder;
        }
```
but interface  IEndpointRouteBuilder no has DefaultHandler. How me implement DefaultHandler?

**Comment by PatrykPorabik** [comment]
Hi Dmitriy,

Probably it's unused now, so if it doesn't exist in interface IEndpointRouteBuilder you should remove it and new generic route should be reworked.

**Comment by PatrykPorabik** [comment]
Hi @dborovsky, how the work is going?

**Comment by dborovsky** [comment]
Hi Patryk. everything fine. I have changed everywere from IRoteBuilder to IEndpointRouteBuilder. Now I am thinking how to do with OData. have one problem with Odata. It implements only IRouteBuilder(how you told me before).  Today I plan to finish. If I will have problems, I will send you code and will ask you for help. 

Sorry for delay. I spent a lot of time to read documentation about Endpoint routing and investigated your current routing on GrandNode.

**Comment by dborovsky** [comment]
@PatrykPorabik @KrzysztofPajak 

I have following old method:

```
public static IRouteBuilder MapLocalizedRoute(this IRouteBuilder routeBuilder,
                string name, string template, object defaults, object constraints, object dataTokens)
{
    if (routeBuilder.DefaultHandler == null)
    {
        throw new ArgumentNullException(nameof(routeBuilder));
    }

    //get registered InlineConstraintResolver
    var inlineConstraintResolver = routeBuilder.ServiceProvider.GetRequiredService<IInlineConstraintResolver>();

    //create new generic route
    routeBuilder.Routes.Add(new LocalizedRoute(routeBuilder.DefaultHandler, name, template,
            new RouteValueDictionary(defaults), new RouteValueDictionary(constraints), 
            new RouteValueDictionary(dataTokens), inlineConstraintResolver));

    return routeBuilder;
}
```



I need change to type **this IEndpointRouteBuilder routeBuilder**. But how me implement adding of new generic router? Interface IEndpointRouteBuilder dosen't have property Routes and I can't use **routeBuilder.Routes.Add...**

**Comment by dborovsky** [comment]
Hi Guys. Can you @KrzysztofPajak @PatrykPorabik  please answer on my previous comment. I though about it and How I see, we need rewrite a bit routing logic to implement endpoint. Maybe I am wrong. Can you tell me how better implelent this

**Comment by PatrykPorabik** [comment]
We would love to help you with this issue, but currently we have opened some different tasks and we are not able to focus on it and check problem's background. Same as you, we would have to jump into code and check what's wrong and what should be reworked. If you are not able to figure out what's wrong, just leave this task for some time and take something else. We told you that will be harder ;)

**Comment by dborovsky** [comment]
I would like to finish. I will rewrite a bit how I see by myself and show you. 
And in parallel I would like to do another task. Which is more important now?

**Comment by PatrykPorabik** [comment]
Well, we thought about two factor authentication. I will assign you to this task and describe it a little. Will it be ok for you?

**Comment by dborovsky** [comment]
sure

**Pull request closed without merging**
