### PR TITLE
#317 publish setting to topic

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by dborovsky** [comment]
Screenshot_1


I can`t undestand why data annotation model dosen`t display value from resources file?  Everythinng else works

**Comment by PatrykPorabik** [comment]
Hi Dmitriy, 

Resources are added during installation, so you should install the whole GrandNode to apply changes or import them manually from file. So everything is ok. I've downloaded this PR and tried to test it. I've installed it and the resource strings has been installed successfuly, but I've encountered different problem. Please logout and try to open published topic. If you are guest or just registered user, you won't see it. IF statement in the code is wrong I guess. Can you check it?

**Comment by dborovsky** [comment]
I updated method PrepareTopicModel. I tested and everything fine now.

**Comment by PatrykPorabik** [comment]
Dmitriy,

Previous thing works perfect, but please mark the box Include in footer row. Then unpublish topic. It will be always visible in the footer, it shouldn't if it's unpublished. And please change the value of "Publish" resource string. We always use "Published" and we would like to use consistent naming.

**Comment by dborovsky** [comment]
done. Check please

**Comment by PatrykPorabik** [comment]
Thanks for contribution!

**Pull request merged**
