### PR TITLE
#619 Add My reviews section to Customer - My Account page

### LINKED ISSUE #619: Add "My reviews" section to Customer - My Account page
Add "My reviews" section to Customer - My Account page and list all reviews created by particular customer.

### PR DESCRIPTION
**Pull request by antigoniapower**
Resolves #619 Add My reviews section to Customer - My Account page
Type: feature

## Solution
- Added menu point 'My reviews' to Customer/My account menu
- Added new tab 'My reviews' to Customer/My account page (implemented front-end + back-end part)
- Added possibility to Hide 'My Reviews' tab to Customer settings in Admin/Configuration page

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hello Olga,

I will check it in a moment. By the way, you can assign your account from GitHub to Visual Studio. As a result, if you commit to our repo, you will appear as a contributor. Now GitHub doesn't recognize your account. Probably you've provided wrong email or username in Visual Studio :)

**Comment by PatrykPorabik** [comment]
Olga,

I would suggest you to add pagination on My Reviews page. Look at the admin@yourstore.com example. Default account has a veery long page with default reviews. Paginated page would be more user friendly. I will merge the current changes, but in the future, you can consider to add the pagination :)

**Comment by PatrykPorabik** [comment]
By the way, there appears one change in the resource string file, can you resolve it?

**Comment by PatrykPorabik** [comment]
Thanks a lot!

**Comment by antigoniapower** [comment]
Hello, Patryk.
Thank you for your review. 
 

> Hello Olga,
> 
> I will check it in a moment. By the way, you can assign your account from GitHub to Visual Studio. As a result, if you commit to our repo, you will appear as a contributor. Now GitHub doesn't recognize your account. Probably you've provided wrong email or username in Visual Studio :)

Unfortunately, I must save the existing e-mail in my VS as I mostly commit to another project outside of GitHub.



> Olga,
> 
> I would suggest you to add pagination on My Reviews page. Look at the [admin@yourstore.com](mailto:admin@yourstore.com) example. Default account has a veery long page with default reviews. Paginated page would be more user friendly. I will merge the current changes, but in the future, you can consider to add the pagination :)

Ok, I will. Should I continue committing to this branch (619_Add_My_reviews_section_to_Customer-My_Account_page) or should I create another branch for it?


> By the way, there appears one change in the resource string file, can you resolve it?

Resolved.

Thank you.

**Comment by PatrykPorabik** [comment]
Olga, 

I will merge this one, next features can be done in different branch. Thanks again for the contribution, hope you enjoyed it!

**Pull request merged**
