### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by Nirmal4G**
As the title says, Update master.

This is required for people who are working with Git Flow addin.

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi,

I'm not able to merge so huge changes. Are you able to divide this PR into many, independent logical PRs? For example each new feature in single PR? It will be easier for us to review changes.

**Comment by Nirmal4G** [comment]
This updating master from develop. Master has not been updated over a year

**Comment by PatrykPorabik** [comment]
But we don't use the master branch. Our main branch on which we are working is develop, that's why we didn't update master.

**Comment by Nirmal4G** [comment]
So, why is it there?

I thought master was the stable branch!
Then which one is the stable branch?

**Comment by PatrykPorabik** [comment]
As it's presented in the README.md file - Active development version: 4.50 (branch develop) and it's our main branch. Master will be removed soon.

**Comment by Nirmal4G** [comment]
Ok, So Can I close the issue?

**Comment by PatrykPorabik** [comment]
Sure. We will stay with your second pull request and focus on it.

**Pull request closed without merging**
