### PR TITLE
Implement Two Factor Authentication

### PR DESCRIPTION
**Pull request by KrzysztofPajak**

### CODE REVIEW

**Comment by dborovsky** [comment]
@KrzysztofPajak  @PatrykPorabik 

I checked. Yes, your code a bit cleaner. Thank you.  How I undestand, you just copied my code and a bit refactor.
I asked you many times, "guys check and tell what change". I had question, but you have never answered. 

Which tasks can I do next, what is important more now?

**Comment by PatrykPorabik** [comment]
I don't know if it can be called as "just copying". Many things was changed. Yesterday more things came, as you can see in the current solution, the login URL doesn't contain secret keys, emails or usernames. The /enable-two-factor-authentication page was accessible also as guest users.

To bo honest, I've answered few times, but only when I was able to check what is wrong. Some things came out only at the time of checking the source code, and once we were in the code, it is more efficient and faster to rewrite it. As you remember, I've checked it few times and few times sent you tips what should be remade, it's not true that we didn't answer. 

In the case of tasks, what about this one - #766 ?

**Comment by dborovsky** [comment]
No, I  meant I could implemented this becouse would like to finish myself. I checked your solution, I like it. Thank you.   

And check please another my PR, when will you free time.

**Comment by dborovsky** [comment]
Can't undestand why you use  for every method "virtual". How I undestood virtual we need if we want to overide method? Maybe I can't undestand something.

**Comment by KrzysztofPajak** [comment]
You can override virtual methods by plugin, so if you want something change in the project you can do this by plugin.

**Pull request merged**
