### PR TITLE
#413-multilanguage-blog-tags

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi Dmitriy,

Thanks for contribution, but after further investigation we have doubts about this functionality. I've downloaded your package and we've made further analysis with core team and we've found some areas, where this feature may cause problems. For example, what if somebody will add the same tag to two different languages? Now it won't work correctly. We haven't thought about this before, but following interference in the search engine friendly pages names may cause many problems due to number of relations. So we think, for now we shouldn't merge it to the main project, because it seems that there should be much more changes, not only localizable field, as we thought before.

**Comment by dborovsky** [comment]
Hi Patryk. Maybe you are right. But I tested localization tags and all fine. Tell me what do I need test in application and change?

**Comment by dborovsky** [comment]
@PatrykPorabik I can do it, but maybe can we have common chat whe we can decide everything?

**Comment by PatrykPorabik** [comment]
To be honest, in the team, we are still talking about that. So I'm not able to give you correct answer on your question. We haven't thought at the first time that it will be problematic. We supposed that it would be as easy as flag translations. If we manage something, I will let you know immediately.

**Comment by dborovsky** [comment]
good. all clear.  How can I be as contributor in your main core team of GrandNode?

**Comment by KrzysztofPajak** [comment]
Conflicting files

**Pull request closed without merging**
