### PR TITLE
Added NBP exchange provider

### PR DESCRIPTION
**Pull request by benys**
I don't know what policy is for adding new features. Please give me a feedback.

I made a little refactor - to add second provider.  It is polish central bank - it provides official exchange rates for currencies in Poland.

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
Kamil,
Thanks for your hard work!
NBP exchange provider should be as a separate plugin. We can add this to our repo but not to the main project. 
Best Regards
Krzysztof

**Comment by benys** [comment]
As I created myself, I had doubts:
a) Currently, the plugin did not inform the normal user - what is exchange provider
b) I did not want to make a separate plugin - because it would be "too simple"
In addition, I made a simple unit test to check whether EUR and PLN are still working at all.
c) A separate repo for 5 lines seems to me that it is overkill

Please close, as the arguments have not convinced.

**Comment by KrzysztofPajak** [comment]
Thanks, we added to main repo.

**Comment by benys** [comment]
Thank you!

**Pull request merged**
