### PR TITLE
 #634 exporting customers issue country

### PR DESCRIPTION
**Pull request by dborovsky**
issue #634

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi,

I've tried to export customers and I faced following problem:
image

**Comment by dborovsky** [comment]
moment please, will check

**Comment by dborovsky** [comment]
Screenshot_1



Screenshot_2



strange... i am still investigating

**Comment by PatrykPorabik** [comment]
Click the Export to XML.

**Comment by dborovsky** [comment]
@PatrykPorabik I fixed. I tested with xml too. everything is fine. Check now

**Comment by dborovsky** [comment]
@PatrykPorabik  did you check?

**Comment by PatrykPorabik** [comment]
Hi,
Sorry for delay and thanks for contribution. It looks like it's ok now.

**Pull request merged**
