### PR TITLE
Add Start/End date fot Topics (Pages)

### LINKED ISSUE #982: Add Start/End date fot Topics (Pages)
Add Start/End date fot Topics (Pages)

### PR DESCRIPTION
**Pull request by badijm**
Resolves #982

## Issue
Add Start/End date fot Topics (Pages)

## Solution
* Add new column to Domain object, set default values, add them to UI

## Testing
1. Set Start/End dates in _Admin/Topic/Edit/_  then check Home page (Footer section)

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
We do not want to force users to enter this datse in any way. They should be empty and completely optional.

**Comment by badijm** [comment]
@PatrykPorabik You mean this columns should be nullable ? Currently, they just filled with Date.Min/Max values.

**Comment by PatrykPorabik** [comment]
Yes, columns should be nullable. We don't see any good reason to enter the data min/max values.

**Comment by badijm** [comment]
@PatrykPorabik I've push new changes. So I've made them nullable, and retrieve only items within date range.

**Comment by PatrykPorabik** [comment]
Hi @badijm 
Sorry for the delay, we had some internal work before analyzing the incoming PRs. I've installed it today and to be honest, I'm not able to save the topic with empty date fields. I still receive the "The value '' is invalid." error.

**Comment by badijm** [comment]
> Hi @badijm
> Sorry for the delay, we had some internal work before analyzing the incoming PRs. I've installed it today and to be honest, I'm not able to save the topic with empty date fields. I still receive the "The value '' is invalid." error.

Okay I will take a look on it asap. Thanks.

Upd: I've remove validation helper for new columns and I was able to save both dates now. 
Upd2: Also put `UIHint` attribute in view model to display empty value in datepicker.

**Comment by PatrykPorabik** [comment]
@badijm Maks, great, it's almost done, however, you forgot about one thing. If the end date gone, I am able to access the topic, which shouldn't be accessible after the end date passes. You should do it in Grand.Web -> Controllers -> TopicController.

**Comment by badijm** [comment]
@PatrykPorabik  I think I've got your idea. I will add simple check in `TopicDetails(string topicId)` method and redirect to home page, if current topic already expired.

image

**Comment by PatrykPorabik** [comment]
Thanks a lot @badijm !

**Comment by PatrykPorabik** [comment]
@badijm we had to make a lot of fixes after merge. Please look at the commit above, you will find there fixes for bugs that we've found during further tests.

**Pull request merged**
