### PR TITLE
Fix of 989: Remove filtering by Published flag

### PR DESCRIPTION
**Pull request by badijm**
Fix of #989 

Ressolve: #989 

Type: **bugfix**

### Solution
No longer filtering Products (`Published` column) for `BestsellerReport.cshtml` view. 

### Breaking changes
None

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
I don't think that it's necessary to create a new param. As you can see, there is a created parameter for it, it's called showHidden. Can you try to use it, instead of creating a new one?

**Comment by badijm** [comment]
It make sense for me. @PatrykPorabik .

Will update my branch soon

**Comment by badijm** [comment]
@PatrykPorabik I've update by PR with new code. Lemme know if it works for ya.

Thx.

**Comment by KrzysztofPajak** [comment]
It does not work. I fixed it, please check this commit:
https://github.com/grandnode/grandnode/commit/73328eb8309f74f2a858e6d7cb5402741a93176a

**Pull request closed without merging**
