### PR TITLE
Moved back to root StackExchange.Redis

### LINKED ISSUE #707: Performance degradation on main page
**Describe the bug**
When accessing the main page, supplied with sample data and a loaded redis cache, the request for the "/" resource takes around 850 ms.
But if I simulate 3 concurrent access, the response time climbs to around 4s!
At first I thought that this had something to do with redis cache, but after switching to memory cache only, the behaviour persisted aggravated by a crash around the 100th request.
Disabling redis cache altogether did shave around 250ms response time for the "/" resource though, BUT the degradation persisted for concurrent requests with similar values...

**To Reproduce**
1. Install Docker
2. Get a container going for mongo and redis
3. Install Grandnode using sample data
4. using a tool such as fiddler or gatling (postman can't simulate repeated concurrent requests, or at least I think not) simulate 3 concurrently sequential requests to "/" resource
5. Notice the response time degradation

**Expected behavior**
I expected that the response time degradation to be smoother. If a single requests takes 850ms, I expected that 3 concurrent ones would take no more than 1.5s.
For a single, isolated request on the "/" resource, using sample data, I would not be satisfied with a response time superior to 300ms.

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
## [Mama I'm coming home!](https://youtu.be/K0siYUjV9UM)
Resolves #707 (partially) and #708
Type: bugfix

## Issue
Redis is heavily used. The home page alone [hits 88 keys](https://github.com/grandnode/grandnode/issues/682#issuecomment-560945439), which translates to over 140 redis commands. Since Redis is single threaded, concurrent requests lock themselves. Another issue is that Microsoft.Extensions.StackExchange tends to work with scripted commands, which tends to run longer. The values are also stored in binary form, which makes the native `redis-cli` almost useless.

## Solution
I started by moving back to the root Stackexchange.Redis NuGet package. This package is more flexible and tends to work with simple commands, which run faster and are easier to troubleshoot. Now, the main page incurs 58 commands. Performance improved on both single requests and concurrent ones.

## Breaking changes
THERE IS NO MORE "SLIDING-WINDOWS"!

## Testing
Extensive Navigation. I suggest running constants "flushall" to simulate the absence of the sliding-windows cache keys (the keys will expire instead of auto-renewing) . As far as I could notice, nothing broke.

ps: sorry, in advance, I couldn't make this one smaller...

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
@Leonardo-Ferreira 
In asynchronous programming is bad practice use method Wait() and Result().

**Comment by Leonardo-Ferreira** [comment]
@KrzysztofPajak  Yes it is, but these are used on sync methods... I will refactor these sync methods on my next pull request... I was just trying to break down things and work with small PR, instead of huge walls of code as you requested previously... This is being carried out [here](https://github.com/Leonardo-Ferreira/grandnode/tree/refactorToAsync). As soon as you merge this one, I'll update my fork, rebase and finish
but if that is not a problem, I can refactor it all in a single batch

**Comment by KrzysztofPajak** [comment]
@Leonardo-Ferreira 
Why we should moved back to root StackExchange.Redis ?

**Comment by Leonardo-Ferreira** [comment]
@KrzysztofPajak for several reasons, being the main one: performance.

1. All commands are based on hash/lua script execution. It really doesn't matter what you're doing, wether it is a simple GET or SET, the command executed is a Hash and that is bad. Bad because atop of executing the inner command (which is not necessarily a single one), Redis has to fetch the hash command. You pay for 2 commands, but only 1 is really needed.

2. The main page alone hits 44 keys. By using the native package, loading the main page means 58 GETs (simples `GET key`). Using the Microsoft implementation, we do a whooping 180 commands (I shit you not my friend). I think that now is a good time to remember that redis is single-threaded (for most of us who are unable to pay for a redis cluster, and even if we do, the extension does not make use of it). There fewer commands we issue in batches, the faster they will run.

3. The SET stores the value of the keys in fields. This makes tools like `redis-cli` become almost useless for troubleshooting

4. The only functionality that we use is the sliding windows, but I have questioned if we really need it: See, our keys lasts for 1 hour. I can bet you that during this one hour, the extra time redis takes executing a reset of the TTL, far exceeds the time required to fetch any information.
As mentioned above, I tested the code using `flushall` and I could not notice anything breaking down... (I did notice that in several moments a cache flush was ordered by some messages, but that's a topic for another PR). And by the way, sliding windows is not an optional feature! [check line 63 here!!!](https://github.com/aspnet/Extensions/blob/master/src/Caching/StackExchangeRedis/src/RedisCache.cs)

For these and others that I can enumerate if necessary, I believe that we should move back to StackExchange.Redis

**Comment by KrzysztofPajak** [comment]
Hi @Leonardo-Ferreira 
Please restore method Get (from CacheService)
Undo changes in files: ProductTagService.cs/SettingService.cs/DiscountService.cs/LocalizationService.cs/StoreMappingService.cs 
Then I try made some performance tests.

**Comment by Leonardo-Ferreira** [comment]
@KrzysztofPajak I re-implemented as you asked!
When testing the performance, remember to test for concurrent requests, simulating 3-5 users simultaneously using the app. On #707 I addressed this "corrosion" of performance. This PR DOES NOT SOLVE that, but it's a start

**Pull request merged**
