### PR TITLE
#472 unit tests - UpdateProductReviewTotalsCommandHandlerTest, ProductReviewService method ProductsReviewByProduct

### PR DESCRIPTION
**Pull request by dborovsky**
#472

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
@dborovsky Is productReviewService is still required on this handler UpdateProductReviewTotalsCommandHandler?

**Comment by KrzysztofPajak** [comment]
@dborovsky I've just check interface IProductReviewService.cs and exists method GetAllProductReviews (one of the param is productId), please use this method and undo changes in IProductReviewService.

**Comment by dborovsky** [comment]
> @dborovsky Is productReviewService is still required on this handler UpdateProductReviewTotalsCommandHandler?

yes, it's required

**Comment by KrzysztofPajak** [comment]
> > @dborovsky Is productReviewService is still required on this handler UpdateProductReviewTotalsCommandHandler?
> 
> yes, it's required

Sorry, I mean _productReviewRepository

**Comment by dborovsky** [comment]
yes, it's required too because handle method uses there: 

`await _productRepository.Collection.UpdateOneAsync(filter, update);`

Maybe we can use too some method from service, but I din't find any usefull service's method for updating.

**Comment by KrzysztofPajak** [comment]
> yes, it's required too because handle method uses there:
> 
> `await _productRepository.Collection.UpdateOneAsync(filter, update);`
> 
> Maybe we can use too some method from service, but I din't find any usefull service's method for updating.

I wrote **_productReviewRepository** not **_productRepository**

**Comment by dborovsky** [comment]
sure, is not required more.  I'll remove it with next commit

**Comment by dborovsky** [comment]
@KrzysztofPajak  Please check and merge

**Comment by dborovsky** [comment]
Guys, check please with last commit. If everything is fine mege. 

P.S. I pass every default params, because mock object dosen't accept this params by default. 
`var reviews = await _productReviewService.GetAllProductReviews(null, null, null, null, null, null, request.Product.Id, 0, 2147483647);`

**Pull request merged**
