### PR TITLE
Hide inventory for auction product type

### LINKED ISSUE #212: Hide inventory for auction product type

### PR DESCRIPTION
**Pull request by Weidaicheng**
Add: Displaystockquantity validation on product maintaince
Add: Admin.Catelog.Product.Fields.DisplayStockQuantity.NotAllowed default resource
Add: Hide inventory for auction product type on product page
Refact: Extract GenerateInStockWithQuantityMessage method and it's unit tests

Resolves #212
Type: **feature**

### CODE REVIEW

**Review by KrzysztofPajak — COMMENTED** [review]
Please update resource string:
Admin.Catelog.Product.Fields.DisplayStockQuantity.NotAllowed
there is a typo.

**Comment by Weidaicheng** [comment]
> Please update resource string:
> Admin.Catelog.Product.Fields.DisplayStockQuantity.NotAllowed
> there is a typo.

Just updated

**Comment by PatrykPorabik** [comment]
Hi @Weidaicheng 
It should be reworked, because we thought about something different. In the admin panel, on product creation page, you have tab called "Inventory". We wanted to hide it with simple if statement for auction products.

**Comment by Weidaicheng** [comment]
> Hi @Weidaicheng
> It should be reworked, because we thought about something different. In the admin panel, on product creation page, you have tab called "Inventory". We wanted to hide it with simple if statement for auction products.

What about admin product editing page and product detail page for old data?

**Comment by TTomu** [comment]
Hi @Weidaicheng 
Admin product details page should hide inventory tab, and no future actions should be called related to inventory, as long as product will not be changed to non-auction.
Product detail page (front-end) should display only current settings of products.

**Comment by Weidaicheng** [comment]
Hi @TTomu I'm still confused about this, can we talk about this by voice call such using skype or anything else? I don't know what software do you usually use, and BTW what's your time zone?

**Comment by TTomu** [comment]
Hi @Weidaicheng 
Don`t close others for information about this issue, by switching to private call ;)
Just ignore old data and hide (display none) if product type is set as auction.

**Comment by Weidaicheng** [comment]
@TTomu Got it, I'll rework this.

**Comment by KrzysztofPajak** [comment]
Conflicting files

**Pull request closed without merging**
