### PR TITLE
#623 adding commission-management

### PR DESCRIPTION
**Pull request by dborovsky**
#623

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi Dmitriy,

There is no need to create additional tab for Commision field. It's enough to include it into main window of vendor edition page. The second case is that you haven't added resource string to default resources file and to upgrade file. And I think it's enough in the case of additional work to do with this task.

**Comment by dborovsky** [comment]
Hi Patryk. 

I`ve alredy added to default resource file _Admin.Vendors.Fields.Commission_ and _Admin.Orders.Products.Commission_. I dont  see inside source code the file update  resource. 

Will this file has same data as default source and additional my new fields?

**Comment by dborovsky** [comment]
Hi guys. If need something change tell me. And tell me which next issue is more relevant?

**Comment by PatrykPorabik** [comment]
I meant about that upgrade file: Grand.Web/App_Data/Localization/Upgrade/EN_450_460.nopres.xml

Rest of things is ok.

**Comment by PatrykPorabik** [comment]
Thanks for contribution!

**Pull request merged**
