### PR TITLE
Order data should be set by checkout controller.

### PR DESCRIPTION
**Pull request by benys**
First – now OrderProcessing is depended on data from checkoutcontroller and db. For example, if somebody order items – customerid, storied are set by checkoutcontroller but cart items are downloaded from DB.

I change that – to set cart items by checkout controller. Now it is possible to make new order (for example by new plugin) without cart items in customer object.

Also I found that OrderSummary downloads from DB not from checkout details.

### CODE REVIEW

**Comment by benys** [comment]
It is very strange. At my computer all test passed.

**Comment by KrzysztofPajak** [comment]
Test was fixed, Thanks!

**Comment by PatrykPorabik** [comment]
Hi,

It has to be analyzed by our team, because that changes may impact on payment method plugins (loaded as a frame in a payment method step) and shipping method plugins. We will keep you informed.

**Comment by benys** [comment]
No problem. I analyzed some random payment plugins and they always return new object (just create empty object).
In my opinion cart items are added to object paymentrequest after payment plugin job. I will be waiting for review!

**Comment by benys** [comment]
Hello,

Would you like to show me where it may be a performance problem?
In my opinion I limited queries to DB at ordersummary to minimum. In other hand I only changed where cartitems are extracted from customer object.

**Pull request closed without merging**
