### PR TITLE
Add possibility to add notes on shipments #620

### LINKED ISSUE #620: Add possibility to add notes on shipments
Add possibility to add notes on shipments

### PR DESCRIPTION
**Pull request by Mac2m**
Resolves #620 
Type: **feature**

## Issue
Add possibility to add notes on shipments.

## Solution
Added possibility to add notes on shipments.

## Testing
Have to add shipment to order.

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hi Maciej,

Thanks for contribution, but I've found some problems. First of all, the button "Display note to customer" doesn't work. And then, the final work of notes should be different. It should be similar to order notes, presented on the screenshot below:
image

In the current situation, I'm not able to add two notes, one visible for admin only and the second one visible for customer.

**Comment by Mac2m** [comment]
I didn't know that it should be like this. I thought that it should be only one note per shipment. 
And what you mean that button doesn't work ? For me it is working perfectly. There's only one button 'Save notes options' that save shipment notes and checkbox value 'Display to customer'.

**Comment by PatrykPorabik** [comment]
Sorry, I meant checkbox, which is visible on the shipment creation window.

**Comment by Mac2m** [comment]
Well, checkbox work for me. What you mean ? I'm checking or unchecking it and then press save button. And all works fine.

**Comment by PatrykPorabik** [comment]
image
And nothing happens when I click it.

**Comment by Mac2m** [comment]
obraz

obraz

Still it looks for me ok. What browser are you using ? I'm testing it on firefox.

**Comment by PatrykPorabik** [comment]
Please try to create new shipment. During the further editing it's working fine. It happens only on the shipment creation.

**Comment by Mac2m** [comment]
Yes you are right. I'll fix it. Thank you.
So if I'm correct, there should be multiple notes on one shipment ?

**Comment by PatrykPorabik** [comment]
Yeah, please try to do it in the same way as the order notes are made.

**Pull request closed without merging**
