### PR TITLE
Support CosmosDB

### PR DESCRIPTION
**Pull request by dongdong-yang**
Resolves #issueNumber  
Type: **feature**

## Issue
Let Grandnode work with Azure CosmosDB

## Solution
Use 2 patterns to work Mongo style DB, one is connectionstring, another is full setup for MongoDBClient. 

## Breaking changes

1. Constructor `MongoDBContext(string connectionString)` is removed, since we read from config file only
2. `SelectList ToSelectList<TEnum>` is added one parameter "bool useLocaliztion = true", because localization is not working before installation
3. Renamed "MongoDBConnectionInfo" to "UseConnectionString"
4. Database connection is only created from config file, no longer using connection string only.

## Farther request:

1. I don't know how to remove changes in readme.md, please rollback it after merge.
2. Some of formatts is from my team's setting, hard to changes, please format them if you don't like it.
3. Maybe the class `DataSettings` should not have so many default value, maybe it should be set in action `InstallController`->`Index`, you can change it.

### CODE REVIEW

**Comment by PatrykPorabik** [comment]
Hello, 

Thanks for great contribution. But we need to make some last touches. Can you check tests in the app? I can see from the output of Travis and AppVeyor that most of tests are failed. Can you fix them?

**Comment by dongdong-yang** [comment]
Yes, I will fix them.

**Comment by PatrykPorabik** [comment]
Hi there,
Any news maybe? We would like to focus on CosmosDB support.

**Comment by burimameti** [comment]
I see is That grandnode is free ,can we change /copyright section  when we customize theproject according our needs

**Comment by PatrykPorabik** [comment]
Yes, GrandNode is free to use for everyone if you leave the "Powered by" information in the footer. To remove the copyright notice, you can purchase the copyright removal key, otherwise you have to keep it in the visible place.

**Comment by burimameti** [comment]
Thank you  for the clarification , if in future i use the GrandNode will
have in mind , I see grand node is for online store dedicated, i am
curious if there is a framework that is built by GrandNode for logistics


Thanks in advance
Burim Ameti

**Pull request closed without merging**
