### PR TITLE
Feature/465 customer reviews tab

### LINKED ISSUE #465: Add customer review tab
Add customer review tab on customer account.

### PR DESCRIPTION
**Pull request by olegbevz**
Resolves #465 
Type: **feature**

## Issue
Add customer review tab on customer account.

image

### CODE REVIEW

**Review by KrzysztofPajak — COMMENTED** [review]
Thank you for contributing!
We want put this feature to the next version, could you move resources from file EN_430_440.nopres.xml to the new file EN_440_450.nopres.xml?

**Comment by olegbevz** [comment]
> Thank you for contributing!
> We want put this feature to the next version, could you move resources from file EN_430_440.nopres.xml to the new file EN_440_450.nopres.xml?

@KrzysztofPajak move resources to EN_440_450.nopres.xml and to defaultResources.grandres.xml (for clean installation). I've also incremented Grand version to 4.50 to enable the migration.

**Review by KrzysztofPajak — COMMENTED** [review]
In the file UpgradeService.cs line 1282 - file name: 440_450.nopres.xml should be EN_440_450.nopres.xml

**Comment by olegbevz** [comment]
> In the file UpgradeService.cs line 1282 - file name: 440_450.nopres.xml should be EN_440_450.nopres.xml

Fixed a typo. Checked that file is really found during update.

**Pull request merged**
