### PR TITLE
Issue 2factor auth

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by dborovsky** [comment]
@PatrykPorabik  your comments from old PR:

I thought we will make some changes and we will merge the 2fa to the main branch, but in fact, there is a lot of things to do in it. First of all, I've updated the GoogleAuthenticator library and it broke 2fa work. We won't accept outdated libraries, which doesn't support .NET Core. So please update it to the newest version and resolve problems. Then please remove the independent tab "Two factor auth" and move it to the Customer info tab, as a section (like external auth). In that case you will need to remove the TwoFactorAuthenticationModel.cs and add it to CustomerInfoModel, like this one: https://github.com/grandnode/grandnode/blob/issue-2factor-auth/Grand.Web/Models/Customer/CustomerInfoModel.cs#L146

When you provide wrong code and press enter, window refreshes and code dissapears. I suppose it's enough to show the notification "Wrong code" and keep the code visible. I've checked some 2fa on external sites and in each case it works in that way. Please commit to issue-2factor-auth if necessary. I suppose tests won't work when you make changes on main feature, I won't check them now.

**Comment by dborovsky** [comment]
@PatrykPorabik @dan269

I have questions.

Why do you use partial class? Why not just class(without partial)?
https://github.com/grandnode/grandnode/blob/issue-2factor-auth/Grand.Web/Models/Customer/CustomerInfoModel.cs#L146

Why we must move TwoFactorAuthModel to CustomerViewModel as nested class?
Typically, a nested class N is created inside of a class C whenever C needs to use something internally which should never be (directly) used outside of C.
We have logic with TwofactorAuthModel outside CustomerViewModel.

For example https://github.com/grandnode/grandnode/blob/issue-2factor-auth/Grand.Web/Controllers/CustomerController.cs#L1502

https://github.com/grandnode/grandnode/blob/issue-2factor-auth/Grand.Web/Controllers/CustomerController.cs#L206

**Comment by dborovsky** [comment]
@PatrykPorabik @KrzysztofPajak @dan269 @TTomu Guys, check please.

**Comment by dborovsky** [comment]
Any news?

**Comment by dborovsky** [comment]
@KrzysztofPajak  @PatrykPorabik  I added tests custommercontroller for 2fa

**Comment by dborovsky** [comment]
@KrzysztofPajak  @PatrykPorabik  I added tests for custommercontroller to test 2fa. Check please and merge or tell me what I must change/refactor. Thank you

**Comment by dborovsky** [comment]
@KrzysztofPajak @PatrykPorabik Any news?

**Comment by PatrykPorabik** [comment]
I will jump into it when we release plugins and themes for the newest version fo GrandNode. It's our  priority right now.

**Comment by dborovsky** [comment]
OK.all clear. If need help with release plugin and themes, tell me.I can help

**Comment by PatrykPorabik** [comment]
I'm not able to install it, can you update the PR to the newest version? We fixed some problems with installation process few moments before release. Thanks.

**Comment by dborovsky** [comment]
@PatrykPorabik  i merged develop branch.

**Comment by PatrykPorabik** [comment]
Thanks

**Comment by PatrykPorabik** [comment]
@dborovsky finally we had some time to focus on this task. Please look at the following branch: 
https://github.com/grandnode/grandnode/tree/issue-2factorauth

We had to rewrite it, firstly because of the approach, we changed it a little, secondly because in current PR is enormous mess. It was impossible to analyze and merge it. As you can see there is over 250 changed files, when in fact only 26 files are related with two factor authentication issue. 

There was still bug with a login, if a two factor authentication was disabled globally, users still were able to login with already enabled authentication. I had to unify and add missing resource strings, I also changed a little login screen just to unify the login screens. You can compare current branch with implemented changes and check how its done now. We have to add one more thing, now it's easy to intercept any user's login without having a password, so you can wait for final commit. 

Of course, we really appreciate your efforts, even if we had to spend a lot of time on tests and rewriting and of course we will credit in the merge message you when we will merge this branch with develop.

**Pull request closed without merging**
