### PR TITLE
Removed BOM from all files

### PR DESCRIPTION
**Pull request by Nirmal4G**
1. Removed BOM from all files
2. Converted all files to UTF-8

### CODE REVIEW

**Comment by Nirmal4G** [comment]
@KrzysztofPajak All Done, You can merge now.

**Comment by KrzysztofPajak** [comment]
Now we are focus on tests of grandnode 4.50.
After publish official version we will merge your pull request.
Thank your contribution!

**Comment by Nirmal4G** [comment]
Any reason, that this PR is blocking you?

These are not code changes. It won't break the build.

**Comment by Nirmal4G** [comment]
closing in favor of issue 600

**Pull request closed without merging**
